### ISSUE TITLE
Doesn't work in the Sandbox OR Mint Steps

### ISSUE THREAD

**Issue by shanerobinson** [fxhash/fxhash-simple-boilerplate#2]
If you Download the ZIP and drop it in the Sandbox, it doesn't work. 
Clicking the "start tests" button does nothing. 

The webpack version works fine. 

* I've tested my own fork of this repo.
* I've tested the ZIP of this repo.
* I've changed names of the ZIP to see if the Sandbox doesn't like "-" in the name for some reason. 

Works fine in my local dev env with both `live-serve` and "Live Server" extension in VSCode.

**Comment by shanerobinson** [comment]
Tried to start the mint process _(to test if it would validate there)_ and get the following error...even though there is clearly an `index.html` file in the root of the folder.

This is this repo's ZIP:

![fxhash_—_mint_Generative_Token](https://user-images.githubusercontent.com/93786/152856389-e669e709-41b6-49bc-83fb-2810af3624a3.jpg)

**Comment by ghost** [comment]
Make sure to zip the files, not the folder. If you right click your folder and zip, then your index.html will actually be in a subfolder and not the root

**Comment by shanerobinson** [comment]
Wow... Ok that was it! **Thank you so much!**
That's going to make it a bit more difficult for regular, non-coder Artists to ZIP up their Project. I'll have to provide very clear instructions and screenshots for the Templates. 😃

**Comment by shanerobinson** [comment]
Thanks again! Closing this.
